[window]
option_as_alt = "Both"
padding = {x=5, y=5}

[font]
size = 17.0

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

# Colors (Gruvbox Material Dark Medium)

[colors.primary]
background = '#282828'
foreground = '#dfbf8e'

[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e78a4e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e3a84e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'
