[window]
option_as_alt = "Both"
padding = {x=5, y=5}

[font]
size = 17.0

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"
