[window]
option_as_alt = "Both"
opacity = 0.8
padding = {x=5, y=5}
decorations = "buttonless"

[font]
size = 15.0

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"
