[font]
size = 13.0

[font.bold]
family="SauceCodePro Nerd Font"
style="Bold"

[font.italic]
family="SauceCodePro Nerd Font"
style="Italic"

[font.bold_italic]
family="SauceCodePro Nerd Font"
style="Bold Italic"

[font.normal]
family="SauceCodePro Nerd Font"
style="Regular"

[window]
padding = {x = 5, y = 5}
opacity = 0.93
decorations = "none"

